%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1:  0.006295
   k2: -0.010754
   p1: -0.000859
   p2:  0.000154
projection_parameters:
   fx: 382.27
   fy: 382.97
   cx: 325.62
   cy: 235.69
